export const APTITUDE_QUESTIONS = [
  { q: 'A train 150m long passes a pole in 15 seconds. Its speed is?', options: ['36 km/h', '54 km/h', '24 km/h', '18 km/h'], answer: 0 },
  { q: 'If 2x + 5 = 17, then x = ?', options: ['4', '5', '6', '7'], answer: 2 },
  { q: 'The average of 5 consecutive numbers is 30. The largest is?', options: ['30', '31', '32', '33'], answer: 2 },
  { q: 'A shopkeeper sells an item at 20% profit. If CP is 500, SP is?', options: ['600', '620', '580', '700'], answer: 0 },
  { q: 'If A:B = 2:3 and B:C = 4:5, then A:C = ?', options: ['8:15', '2:5', '8:12', '3:5'], answer: 0 },
  { q: 'A clock loses 5 minutes per hour. In a day it loses?', options: ['120 min', '60 min', '100 min', '90 min'], answer: 0 },
  { q: 'The probability of getting heads in 3 coin tosses (at least 2)?', options: ['1/2', '3/8', '1/4', '5/8'], answer: 0 },
  { q: 'If 15 men build a wall in 10 days, 5 men build it in?', options: ['30 days', '20 days', '25 days', '40 days'], answer: 0 },
  { q: 'Simple interest on 1000 at 5% for 2 years is?', options: ['100', '50', '150', '200'], answer: 0 },
  { q: 'The next number in 2, 6, 12, 20, 30, ? is?', options: ['42', '40', '44', '46'], answer: 0 },
];

export const VOCABULARY_QUESTIONS = [
  { q: 'Synonym of "Abundant"?', options: ['Scarce', 'Plentiful', 'Tiny', 'Weak'], answer: 1 },
  { q: 'Antonym of "Ancient"?', options: ['Old', 'Modern', 'Historic', 'Classic'], answer: 1 },
  { q: 'Synonym of "Benevolent"?', options: ['Cruel', 'Kind', 'Selfish', 'Harsh'], answer: 1 },
  { q: 'Antonym of "Brave"?', options: ['Bold', 'Courageous', 'Cowardly', 'Daring'], answer: 2 },
  { q: 'Synonym of "Diligent"?', options: ['Lazy', 'Hardworking', 'Slow', 'Idle'], answer: 1 },
  { q: 'Antonym of "Generous"?', options: ['Giving', 'Stingy', 'Kind', 'Charitable'], answer: 1 },
  { q: 'Synonym of "Ephemeral"?', options: ['Eternal', 'Short-lived', 'Permanent', 'Long'], answer: 1 },
  { q: 'Antonym of "Humble"?', options: ['Modest', 'Arrogant', 'Meek', 'Polite'], answer: 1 },
  { q: 'Synonym of "Resilient"?', options: ['Fragile', 'Tough', 'Weak', 'Brittle'], answer: 1 },
  { q: 'Antonym of "Transparent"?', options: ['Clear', 'Opaque', 'Visible', 'Open'], answer: 1 },
];

export const TECHNICAL_QUESTIONS = {
  C: [
    { q: 'Size of int in C (typical)?', options: ['2 bytes', '4 bytes', '8 bytes', 'Depends on system'], answer: 3 },
    { q: 'Which is NOT a C keyword?', options: ['int', 'float', 'string', 'char'], answer: 2 },
    { q: 'Default return type of main()?', options: ['void', 'int', 'char', 'float'], answer: 1 },
    { q: 'Operator for address-of?', options: ['*', '&', '#', '@'], answer: 1 },
    { q: 'Header for printf?', options: ['<conio.h>', '<stdio.h>', '<math.h>', '<string.h>'], answer: 1 },
    { q: 'Which is a loop construct?', options: ['if', 'switch', 'for', 'break'], answer: 2 },
    { q: 'Sizeof(char) is?', options: ['1 byte', '2 bytes', '4 bytes', '8 bytes'], answer: 0 },
    { q: 'Which is correct pointer declaration?', options: ['int *p;', 'ptr p;', 'int p*;', 'pointer p;'], answer: 0 },
    { q: 'String terminator in C?', options: ['\\n', '\\0', '\\t', '\\r'], answer: 1 },
    { q: 'malloc returns?', options: ['int', 'void*', 'char', 'float'], answer: 1 },
  ],
  'C++': [
    { q: 'C++ is a?', options: ['Procedural', 'Object-oriented', 'Functional', 'Logic'], answer: 1 },
    { q: 'Which is NOT a C++ feature?', options: ['Encapsulation', 'Inheritance', 'Garbage collection', 'Polymorphism'], answer: 2 },
    { q: 'Default access in class?', options: ['public', 'private', 'protected', 'friend'], answer: 1 },
    { q: 'Operator for scope resolution?', options: ['::', ':', '.', '->'], answer: 0 },
    { q: 'Which is a virtual function keyword?', options: ['virtual', 'override', 'abstract', 'final'], answer: 0 },
    { q: 'STL stands for?', options: ['Standard Template Library', 'Static Type Lib', 'System Tool Lib', 'Simple Type Lib'], answer: 0 },
    { q: 'Which is a container in STL?', options: ['vector', 'array', 'list', 'All of the above'], answer: 3 },
    { q: 'Constructor returns?', options: ['void', 'nothing', 'int', 'object'], answer: 1 },
    { q: 'Friend function can access?', options: ['public only', 'private members', 'protected only', 'nothing'], answer: 1 },
    { q: 'new operator returns?', options: ['int', 'pointer', 'reference', 'void'], answer: 1 },
  ],
  Java: [
    { q: 'Java is a?', options: ['Compiled only', 'Interpreted only', 'Both compiled and interpreted', 'Neither'], answer: 2 },
    { q: 'Java packages are imported using?', options: ['include', 'import', 'using', 'require'], answer: 1 },
    { q: 'Main method signature?', options: ['public void main()', 'public static void main(String[] a)', 'static main()', 'void main(String a)'], answer: 1 },
    { q: 'Which is NOT a Java keyword?', options: ['class', 'interface', 'goto', 'function'], answer: 3 },
    { q: 'JVM stands for?', options: ['Java Virtual Machine', 'Java Variable Method', 'Java Verified Module', 'Java Visual Machine'], answer: 0 },
    { q: 'Default value of boolean?', options: ['true', 'false', '0', 'null'], answer: 1 },
    { q: 'Which is a wrapper class?', options: ['int', 'Integer', 'char', 'boolean'], answer: 1 },
    { q: 'String in Java is?', options: ['mutable', 'immutable', 'primitive', 'thread-safe only'], answer: 1 },
    { q: 'Inheritance uses?', options: ['implements', 'extends', 'inherits', 'uses'], answer: 1 },
    { q: 'Garbage collection is?', options: ['manual', 'automatic', 'not supported', 'optional'], answer: 1 },
  ],
  Python: [
    { q: 'Python is?', options: ['Compiled', 'Interpreted', 'Assembly', 'Machine code'], answer: 1 },
    { q: 'Python file extension?', options: ['.p', '.py', '.pyt', '.python'], answer: 1 },
    { q: 'Which is a Python list?', options: ['{1,2}', '(1,2)', '[1,2]', '<1,2>'], answer: 2 },
    { q: 'Python comment symbol?', options: ['//', '#', '/*', '--'], answer: 1 },
    { q: 'Which is immutable?', options: ['list', 'dict', 'tuple', 'set'], answer: 2 },
    { q: 'len([1,2,3]) returns?', options: ['2', '3', '4', 'error'], answer: 1 },
    { q: 'Python keyword for function?', options: ['function', 'def', 'func', 'lambda only'], answer: 1 },
    { q: 'Which is a dictionary?', options: ['{1:2}', '[1:2]', '(1:2)', '<1:2>'], answer: 0 },
    { q: 'Output of 3//2?', options: ['1.5', '1', '2', '0'], answer: 1 },
    { q: 'Which is NOT a Python data type?', options: ['int', 'str', 'char', 'float'], answer: 2 },
  ],
};
